[kube-state-metrics] Docker images updates - 2023-12-15-104208
GoogleCloudPlatform/kube-state-metrics-docker pull request #52
Opened 2023-12-15 13:32 UTC by AdrianManiek

2023-12-20 12:17 UTC, armandomiani requested changes
no need to add 1.9 (older version)

2023-12-20 12:18 UTC, armandomiani requested changes
no need to readd 1.9 (older version)

2023-12-20 15:10 UTC, kaichengyan approved these changes

2023-12-28 10:46 UTC, armandomiani approved these changes

2023-12-28 11:05 UTC, merged